# Generated by Django 6.0 on 2025-12-28 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Draft', max_length=20)),
                ('oath_user', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the holiday')),
                ('discount_type', models.CharField(choices=[('Full', 'Full Holiday (100% Off)'), ('Percentage', 'Percentage Discount (%)'), ('Amount', 'Fixed Amount Discount (Rs)')], default='Full', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Value for percentage or amount discount', max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_holidaymonth',
                'ordering': ['-year', 'month'],
                'indexes': [models.Index(fields=['year', 'month'], name='core_holida_year_779adf_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Half Paid', 'Half Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
            ],
            options={
                'db_table': 'core_student',
                'indexes': [models.Index(fields=['name'], name='core_studen_name_a58b91_idx')],
            },
        ),
        migrations.CreateModel(
            name='DraftPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fee for this payment period', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Accepted', 'Accepted'), ('Partial', 'Partial'), ('Declined', 'Declined'), ('Half Paid', 'Half Paid')], default='Draft', max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('oath_user', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the discount')),
                ('discount_type', models.CharField(choices=[('Full', 'Full Holiday (100% Off)'), ('Percentage', 'Percentage Discount (%)'), ('Amount', 'Fixed Amount Discount (Rs)')], default='Full', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Value for percentage or amount discount', max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.student')),
            ],
            options={
                'db_table': 'core_studentdiscount',
                'ordering': ['-year', 'month', 'student__name'],
                'indexes': [models.Index(fields=['student', 'year', 'month'], name='core_studen_student_f7345d_idx'), models.Index(fields=['year', 'month'], name='core_studen_year_510257_idx')],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
