# Generated by Django 6.0 on 2025-12-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_draftexpense_user_draftpayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftexpense',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='draftpayment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
