# Generated by Django 6.0 on 2025-12-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_draftexpense_status_draftpayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='draftpayment',
            name='payment_type',
        ),
    ]
