# Generated by Django 6.0 on 2025-12-23 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_paid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
