# Generated by Django 6.0 on 2025-12-26 13:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_draftpayment_student_student_last_paid_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='last_paid_date',
            field=models.DateField(default=core.models.get_first_of_month),
        ),
    ]
