# Generated by Django 5.2.9 on 2025-12-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_expense_id_alter_payment_id_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_paid_date',
        ),
    ]
