# Generated by Django 5.2.9 on 2025-12-27 20:54

from django.db import migrations


class SafeRemoveField(migrations.operations.base.Operation):
    reduces_to_sql = True
    reversible = True

    def __init__(self, model_name, name):
        self.model_name = model_name
        self.name = name

    def state_forwards(self, app_label, state):
        try:
            state.remove_field(app_label, self.model_name.lower(), self.name)
        except KeyError:
            pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        try:
            field = model._meta.get_field(self.name)
        except Exception:
            return
        try:
            schema_editor.remove_field(model, field)
        except Exception:
            pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # No safe way to restore without knowing original definition.
        pass

    def describe(self):
        return f"Safely remove field {self.name} from {self.model_name}"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_expense_id_alter_payment_id_alter_student_id'),
    ]

    operations = [
        SafeRemoveField(
            model_name='student',
            name='last_paid_date',
        ),
    ]
