# Generated by Django 5.2.9 on 2025-12-27 20:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_student_last_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_paid_date',
            field=models.DateField(default=core.models.get_first_of_month),
        ),
    ]
