# Generated by Django 5.2.9 on 2025-12-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_student_last_paid_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
