# Generated by Django 6.0 on 2025-12-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentmonthlystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
