# Generated by Django 5.2.9 on 2025-12-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_created_at_student_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
