# Generated by Django 6.0 on 2025-12-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_student_created_at_to_created_date'),
        ('core', '0013_unique_student_name'),
    ]

    operations = [
    ]
