# Generated by Django 6.0 on 2025-12-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20251227_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpayment',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fee for this payment period', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='draftexpense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='draftpayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='draftpayment',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='draftpayment',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmonthlystatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
