# Generated by Django 6.0 on 2025-12-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_monthly_fee_to_draftpayment'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_student RENAME COLUMN fixed_fee TO monthly_fee;",
            reverse_sql="ALTER TABLE core_student RENAME COLUMN monthly_fee TO fixed_fee;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_student RENAME COLUMN created_at TO created_date;",
            reverse_sql="ALTER TABLE core_student RENAME COLUMN created_date TO created_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_student DROP COLUMN IF EXISTS temporary_fee;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "ALTER TABLE core_student DROP COLUMN IF EXISTS last_paid_date;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
