# Generated by Django 6.0 on 2025-12-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_student_schema'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_payment RENAME TO core_draftpayment;",
            reverse_sql="ALTER TABLE core_draftpayment RENAME TO core_payment;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_expense RENAME TO core_draftexpense;",
            reverse_sql="ALTER TABLE core_draftexpense RENAME TO core_expense;"
        ),
        # Fix column names in core_draftpayment
        migrations.RunSQL(
            "ALTER TABLE core_draftpayment RENAME COLUMN student_name TO name;",
            reverse_sql="ALTER TABLE core_draftpayment RENAME COLUMN name TO student_name;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_draftpayment RENAME COLUMN created_at TO created_date;",
            reverse_sql="ALTER TABLE core_draftpayment RENAME COLUMN created_date TO created_at;"
        ),
        # Fix column names in core_draftexpense
        migrations.RunSQL(
            "ALTER TABLE core_draftexpense RENAME COLUMN expense_name TO name;",
            reverse_sql="ALTER TABLE core_draftexpense RENAME COLUMN name TO expense_name;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_draftexpense RENAME COLUMN created_at TO created_time;",
            reverse_sql="ALTER TABLE core_draftexpense RENAME COLUMN created_time TO created_at;"
        ),
        # Add missing columns to core_draftpayment
        migrations.RunSQL(
            "ALTER TABLE core_draftpayment ADD COLUMN IF NOT EXISTS monthly_fee numeric(10,2);",
            reverse_sql="ALTER TABLE core_draftpayment DROP COLUMN IF EXISTS monthly_fee;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_draftpayment ADD COLUMN IF NOT EXISTS oath_user varchar(255);",
            reverse_sql="ALTER TABLE core_draftpayment DROP COLUMN IF EXISTS oath_user;"
        ),
        # Add missing columns to core_draftexpense
        migrations.RunSQL(
            "ALTER TABLE core_draftexpense ADD COLUMN IF NOT EXISTS oath_user varchar(255);",
            reverse_sql="ALTER TABLE core_draftexpense DROP COLUMN IF EXISTS oath_user;"
        ),
    ]
