# Generated by Django 6.0 on 2025-12-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_payment_expense_tables'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_draftpayment DROP COLUMN IF EXISTS name;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
