# Generated by Django 6.0 on 2025-12-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_created_date_student_created_at'),
        ('core', '0018_remove_name_column_from_draftpayment'),
    ]

    operations = [
    ]
