# Generated by Django 6.0 on 2025-12-28 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_monthly_payments_to_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Draft', max_length=20)),
                ('oath_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fee for this payment period', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Accepted', 'Accepted'), ('Partial', 'Partial'), ('Declined', 'Declined'), ('Half Paid', 'Half Paid')], default='Draft', max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('oath_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the holiday')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_holidaymonth',
                'ordering': ['-year', 'month'],
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fixed_fee',
            new_name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_paid_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='temporary_fee',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='core_studen_name_a58b91_idx'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='core_student',
        ),
        migrations.AddField(
            model_name='draftexpense',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftpayment',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student'),
        ),
        migrations.AddField(
            model_name='draftpayment',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='holidaymonth',
            index=models.Index(fields=['year', 'month'], name='core_holida_year_779adf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaymonth',
            unique_together={('year', 'month')},
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
