# Generated by Django 6.0 on 2025-12-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_holiday_month_model'),
        ('core', '0022_add_holiday_month_only'),
    ]

    operations = [
    ]
