# Generated by Django 6.0 on 2025-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20251228_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaymonth',
            name='discount_type',
            field=models.CharField(choices=[('Full', 'Full Holiday (100% Off)'), ('Percentage', 'Percentage Discount (%)'), ('Amount', 'Fixed Amount Discount (Rs)')], default='Full', max_length=20),
        ),
        migrations.AddField(
            model_name='holidaymonth',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value for percentage or amount discount', max_digits=10),
        ),
    ]
