# Generated by Django 6.0 on 2025-12-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_holidaymonth_discount_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the discount')),
                ('discount_type', models.CharField(choices=[('Full', 'Full Holiday (100% Off)'), ('Percentage', 'Percentage Discount (%)'), ('Amount', 'Fixed Amount Discount (Rs)')], default='Full', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Value for percentage or amount discount', max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.student')),
            ],
            options={
                'db_table': 'core_studentdiscount',
                'ordering': ['-year', 'month', 'student__name'],
                'indexes': [models.Index(fields=['student', 'year', 'month'], name='core_studen_student_f7345d_idx'), models.Index(fields=['year', 'month'], name='core_studen_year_510257_idx')],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
